name: cfeccDNA_analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:

  - python=3.10
  - r-base=4.3.3
  - pip           
  
 
  - zlib          
  - libxml2
  - libiconv
  
 
  - git
  - make
  - pkg-config
  - gcc_linux-64
  - gxx_linux-64

  
  - r-remotes
  - r-optparse
  - r-dplyr
  - r-ggplot2
  - r-stringr
  - r-tidyr
  - r-knitr
  - r-rmarkdown
  - r-readxl 
  - r-mgsub

  
  - bioconductor-biostrings
  - bioconductor-bsgenome
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-rsamtools
  - bioconductor-rtracklayer
  - bioconductor-bsgenome.hsapiens.ucsc.hg38

  
  - bedtools
  - samtools
  - bwa
  - macs3        
  
 
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pysam
  
 